#!/usr/bin/env bash
# install and configure HAproxy load balancer

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo tee -a /etc/haproxy/haproxy.cfg << 'EOF'
    frontend http_front
        bind *:80
        mode http
        default_backend http_back
    
    backend http_back
        balance roundrobin
        server 418248-web-01 54.152.4.31:80 check
        server 418248-web-02 54.237.88.120:80 check
EOF

service haproxy start