#!/usr/bin/env bash
#script to debug our nginx configuration and make it listen on port 80

#You first delete the configuration in your sites-enabled then make it sink with your sites-available by linking them
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
