#!/usr/bin/env bash
# This script fixes a nginx server listening on the wrong port
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
kill -s HUP "$(cat /run/nginx.pid)"
