#!/usr/bin/env bash
# This sript makes nignx run as nginx user and  listen on all active IPs on port 8080

# Stop nginx service
service nginx stop

# Modify nginx configuration to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Ensure nginx listens on all active IPs on port 8080
sed -i 's/listen\s*80;/listen *:8080;/g' /etc/nginx/sites-available/default

#sets the permissions of the nginx configuration file to read-write for the owner and read-only for others.
chmod 644 /etc/nginx/nginx.conf

#kills the Apache2 process if it's running to avoid conflict.
pkill apache2

# Start nginx service
sudo service nginx restart

