#!/usr/bin/env bash
# This sript makes nignx run as nginx user and  listen on all active IPs on port 8080

# Stop nginx service
service nginx stop

# Modify nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Ensure nginx listens on all active IPs on port 8080
sed -i 's/listen\s*80;/listen *:8080;/g' /etc/nginx/sites-available/default

# Start nginx service
service nginx start
